#!/usr/bin/env python3
# scripts/gen_conway_version.py
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Command64 project contributors
#
# Generate conwayver.s -- the CASM-native version source for CONWAY -- from
# two persistent, checked-in inputs:
#
#   CONWAY_VERSION   app-owned "MAJOR.MINOR.STAGE" (e.g. "0.4.1"), hand-bumped
#   BUILD_CONWAY     persistent build counter (first line)
#
# The old ca65 mechanism was `.define VERSION_MAJOR "0"` ... plus a generated
# `build_conway.inc` supplying `.define BUILD_NUMBER "1063"`, concatenated in
#   exitBanner:  .byte "CONWAY v", VERSION_MAJOR, ".", ..., BUILD_NUMBER, PetCr, 0
#   menuVersion: .byte VERSION_MAJOR, ".", ..., BUILD_NUMBER
# Native CASM has no `.define` text-substitution macro.
#
# This file emits BOTH version strings CONWAY needs:
#
#   EXITBANNER   printed through CHROUT on exit -> PETSCII. On Command 64's
#                mixed-case charset CHROUT renders shifted PETSCII $C1-$DA as
#                an UPPERCASE glyph and unshifted $41-$5A as lowercase. The
#                frozen ca65 build emits exactly:
#                  C3 CF CE D7 C1 D9  20 56  "0.4.1.1063"  0D 00
#                = shifted "CONWAY", space, unshifted 'v' ($56 -> lowercase
#                glyph), the dotted version+build, CR, NUL. gen reproduces
#                these bytes exactly -- no visual change.
#
#   MENUVERSION  copied verbatim into screen RAM by a MENU_VERSION_LEN-counted
#                loop (no terminator). Screen codes. Digits $30-$39 and '.'
#                $2E are identity under the screen-code transform, so a plain
#                native string literal emits the correct bytes. The frozen
#                ca65 build emits: 30 2E 34 2E 31 2E 31 30 36 33.
#
# Also emits MENU_VERSION_LEN as a plain literal equate (CASM named-constant
# RHS must be a bare literal -- it cannot be `menuVersionEnd - menuVersion`).
#
# The generated file is a build product: NOT checked in. Its two inputs ARE
# checked in and ARE part of conway.ref.hex's source-hash gate, so a version
# bump forces a deliberate manifest regeneration, never a silent stale ship.

import argparse
import sys
from pathlib import Path

APP_NAME = "CONWAY"
PETSCII_CR = 0x0D


def shifted_letter_bytes(text: str) -> list[int]:
    out = []
    for ch in text:
        if not ("A" <= ch <= "Z"):
            raise SystemExit(f"gen_conway_version: APP_NAME must be A-Z only, got {text!r}")
        out.append(ord(ch) + 0x80)  # unshifted $41-$5A -> shifted $C1-$DA
    return out


def check_digits(text: str) -> None:
    for ch in text:
        if not (ch.isdigit() or ch == "."):
            raise SystemExit(f"gen_conway_version: unexpected char {ch!r} in {text!r}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version-file", required=True, help="path to CONWAY_VERSION")
    ap.add_argument("--build-file", required=True, help="path to BUILD_CONWAY")
    ap.add_argument("--out", required=True, help="path to write conwayver.s")
    args = ap.parse_args()

    ver = Path(args.version_file).read_text().strip()
    parts = ver.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise SystemExit(
            f"gen_conway_version: CONWAY_VERSION must be MAJOR.MINOR.STAGE digits, got {ver!r}"
        )

    build_line = Path(args.build_file).read_text().splitlines()[0].strip()
    if not build_line.isdigit():
        raise SystemExit(
            f"gen_conway_version: BUILD_CONWAY first line must be digits, got {build_line!r}"
        )

    digits = f"{ver}.{build_line}"
    check_digits(digits)

    # $20 = space, $56 = unshifted 'v' -> lowercase glyph on the mixed-case
    # charset (matches the frozen ca65 exitBanner byte for byte).
    name_hex = ", ".join(f"${b:02X}" for b in shifted_letter_bytes(APP_NAME)) + ", $20, $56"

    body = (
        "; CONWAYVER.S -- GENERATED BY SCRIPTS/GEN_CONWAY_VERSION.PY\n"
        "; DO NOT EDIT. DO NOT CHECK IN. REGENERATED AT BUILD TIME FROM\n"
        "; CONWAY_VERSION + BUILD_CONWAY (BOTH CHECKED IN, BOTH IN\n"
        "; CONWAY.REF.HEX'S SOURCE-HASH GATE). SEE THE 2026-09-03 CONWAY\n"
        "; CASM-NATIVE MIGRATION PLAN.\n"
        ";\n"
        f"; EXITBANNER RENDERS AS: {APP_NAME} v{digits}  (APP NAME UPPERCASE\n"
        "; GLYPH, LOWERCASE V, DIGITS). MENUVERSION IS THE SCREEN-RAM COPY.\n"
        "\n"
        f"; (CONWAY.S MUST DEFINE MENU_VERSION_LEN = {len(digits)} -- NOT EMITTED\n"
        "; HERE: A NAMED CONSTANT IN AN .INCLUDE'D FILE IS RELOCATABLE UNDER\n"
        "; CASM 0.6.2 AND WOULD EMIT SPURIOUS R6 ENTRIES.)\n"
        "\n"
        "EXITBANNER:\n"
        f'    .BYTE {name_hex}    ; SHIFTED "{APP_NAME}" + SPACE + LOWERCASE V\n'
        f'    .BYTE "{digits}", ${PETSCII_CR:02X}, $00\n'
        "\n"
        "MENUVERSION:\n"
        f'    .BYTE "{digits}"    ; SCREEN-CODE IDENTITY (DIGITS + DOTS); NO TERMINATOR\n'
    )

    # Uppercase the whole file -- check_casm_source_bytes.py rejects $61-$7A
    # anywhere. The payload strings are digits/dots only, so uppercasing is a
    # no-op on them.
    Path(args.out).write_text(body.upper())
    return 0


if __name__ == "__main__":
    sys.exit(main())
