#!/usr/bin/env python3
# scripts/gen_conway_menu.py
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Command64 project contributors
#
# Generate conwaymenu.s -- CONWAY's menu / simulation-status text, emitted as
# explicit C64 *screen-code* .BYTE data for native CASM.
#
# The retired ca65 build stored these strings as `.byte "..."` literals inside
# `screencode_mixed` / `petscii_mixed` blocks (include/ca65/screencode.inc),
# ca65 .CHARMAP macros that remap the ASCII source to screen codes because the
# bytes are written straight into screen RAM ($0400), never through CHROUT.
# Native CASM has no .CHARMAP / .ENCODING / .MACRO / .REPEAT, and its string
# literals emit raw bytes -- so the transform is done here, once, mechanically,
# and the result is a reviewable .BYTE table.
#
# Screen-code transform (exactly the ca65 charmap in screencode.inc):
#   0x20..0x3F   -> identity        (space, digits, punctuation)
#   0x61..0x7A   -> b - 0x60        ('a'->$01 ... 'z'->$1A)
#   anything else -> hard error     (uppercase letters etc. are not used by
#                                    any CONWAY string, nor mapped by ca65)
#
# Two kinds of entry:
#   terminated -- copied by copyMenuString until $00; emits the bytes then
#                 $00, with the End label on the $00 (matches ca65 exactly).
#   counted    -- copied by a length-counted loop; NO terminator. Their
#                 lengths are the STATUS_TEXT_LEN / MENU_NONE_LEN equates,
#                 emitted here as bare literals (CASM cannot put `end - start`
#                 on a named-constant RHS).
#
# Build product: NOT checked in. STRINGS below is the source of truth;
# scripts/check_conway_layout.py imports it to re-verify every layout
# invariant the ca65 `.assert` directives used to guard.

import argparse
import sys
from pathlib import Path

# (label, text, terminated?) -- order matches the ca65 source.
STRINGS: list[tuple[str, str, bool]] = [
    ("menuTitle", "conway multiverse", True),
    ("menuRule", "-----------------", True),
    ("menuSelect", "select preset:", True),
    ("menuPreset1", "1 conway life       b3/s23", True),
    ("menuPreset2", "2 ant colony        b3/s234", True),
    ("menuPreset3", "3 world on fire     b34/s23", True),
    ("menuPreset4", "4 blinkers          b345/s2", True),
    ("menuPreset5", "5 mazectric         b3/s1234", True),
    ("menuPreset6", "6 maze              b3/s12345", True),
    ("menuPreset7", "7 life no death     b3/s0-8", True),
    ("menuPreset8", "8 coral             b3/s45678", True),
    ("menuPreset9", "9 assimilation      b3/s4567", True),
    ("menuCurrent", "current rule:", True),
    ("menuBirthLabel", "birth:", True),
    ("menuSurvLabel", "survival:", True),
    ("menuControls1", "1-9:preset  b/s:edit", True),
    ("menuControls2", "return:run  r:random run", True),
    ("menuControls3", "q or run/stop:exit", True),
    ("menuPromptNormal", "q:exit to shell", True),
    ("menuPromptBirth", "birth: press 0-8 to toggle", True),
    ("menuPromptSurvival", "survival: press 0-8 to toggle", True),
    ("menuNoneText", "none", False),
    ("statusText", "sp:pause r:rnd c:clear q:menu  gen:00000", False),
]

# equate name -> source string label (length becomes a bare literal)
LENGTH_EQUATES = [
    ("MENU_NONE_LEN", "menuNoneText"),
    ("STATUS_TEXT_LEN", "statusText"),
]

_TEXT = {label: text for label, text, _ in STRINGS}


def to_screencode(text: str, label: str) -> list[int]:
    out = []
    for ch in text:
        b = ord(ch)
        if 0x20 <= b <= 0x3F:
            out.append(b)
        elif 0x61 <= b <= 0x7A:
            out.append(b - 0x60)
        else:
            raise SystemExit(
                f"gen_conway_menu: {label!r}: char {ch!r} (0x{b:02X}) is outside the "
                f"screen-code transform domain (0x20-0x3F, 0x61-0x7A)"
            )
    return out


def emit() -> str:
    lines = [
        "; CONWAYMENU.S -- GENERATED BY SCRIPTS/GEN_CONWAY_MENU.PY",
        "; DO NOT EDIT. DO NOT CHECK IN. SCREEN-CODE .BYTE DATA FOR CONWAY'S",
        "; MENU / SIMULATION-STATUS TEXT (WAS CA65 .CHARMAP MACROS). SEE THE",
        "; 2026-09-03 CONWAY CASM-NATIVE MIGRATION PLAN.",
        "",
    ]
    # The MENU_NONE_LEN / STATUS_TEXT_LEN equates are NOT emitted here: a
    # named constant defined in an .INCLUDE'd file is treated by CASM 0.6.2 as
    # relocatable (spurious R6 entries on every referencing operand). They are
    # defined inline in conway.s instead; check_conway_layout.py keeps both
    # sides in sync. Expected values:
    for eq, src in LENGTH_EQUATES:
        lines.append(f"; (conway.s must define {eq} = {len(_TEXT[src])})")
    lines.append("")
    # CASM tracks source column in an 8-bit counter (CASM_DIAG_SOURCE_LOCATION
    # _OVERFLOW past 255). Keep every emitted line well under that: <=12 bytes
    # per .BYTE line, and the readable annotation on its own comment line.
    PER_LINE = 12
    for label, text, term in STRINGS:
        codes = to_screencode(text, label)
        lines.append(f'; "{text}"')
        lines.append(f"{label.upper()}:")
        for i in range(0, len(codes), PER_LINE):
            chunk = ", ".join(f"${b:02X}" for b in codes[i:i + PER_LINE])
            lines.append(f"    .BYTE {chunk}")
        lines.append(f"{label.upper()}END:")
        if term:
            lines.append("    .BYTE $00")
    lines.append("")
    # Whole file must be uppercase ASCII: check_casm_source_bytes.py rejects
    # $61-$7A anywhere, comments included. The `; "..."` annotations are the
    # lowercase-rendered on-screen text shown uppercased for the gate.
    return ("\n".join(lines) + "\n").upper()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="path to write conwaymenu.s")
    args = ap.parse_args()
    Path(args.out).write_text(emit())
    return 0


if __name__ == "__main__":
    sys.exit(main())
