#!/usr/bin/env python3
# scripts/gen_label_version.py
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Command64 project contributors
#
# Generate src/external/label/labelver.s -- the CASM-native version-banner
# source for LABEL -- from two persistent, checked-in inputs:
#
#   LABEL_VERSION   app-owned "MAJOR.MINOR.STAGE" (e.g. "0.4.0"), hand-bumped
#   BUILD_LABEL     persistent build counter (first line)
#
# The old ca65 mechanism was `.define VERSION_MAJOR "0"` ... plus a generated
# `build_label.inc` supplying `.define BUILD_NUMBER "1047"`, concatenated in a
# `.byte "LABEL V", VERSION_MAJOR, ".", ... , BUILD_NUMBER` line. Native CASM
# has no `.define` text-substitution macro.
#
# Banner format matches DEBUG's ("DEBUG v0.5.0.1128"): the app name renders as
# an UPPERCASE glyph, then a lowercase " v", then the dotted version+build.
# Command 64 runs the mixed-case (lowercase) charset, where CHROUT of:
#   - shifted PETSCII $C1-$DA  -> UPPERCASE glyph
#   - unshifted PETSCII $41-$5A -> lowercase glyph
# So the app name is emitted as explicit *shifted* letter bytes (a few
# reviewed values), and " v<ver>.<build>" as a plain native string literal
# (space, lowercase 'v' = $56, digits and '.' are charmap-invariant).
#
# The generated file is a build product: NOT checked in. Its two inputs ARE
# checked in and ARE part of label.ref.hex's source-hash gate, so a version
# bump forces a deliberate manifest regeneration, never a silent stale ship.

import argparse
import sys
from pathlib import Path

APP_NAME = "LABEL"
PETSCII_CR = 0x0D


def shifted_letter_bytes(text: str) -> list[int]:
    out = []
    for ch in text:
        if not ("A" <= ch <= "Z"):
            raise SystemExit(f"gen_label_version: APP_NAME must be A-Z only, got {text!r}")
        out.append(ord(ch) + 0x80)  # unshifted $41-$5A -> shifted $C1-$DA
    return out


def check_digits(text: str) -> None:
    # Only digits and '.' -- these are charmap-invariant and legal in a native
    # CASM string literal. Letters (any case) are NOT: ASCII lowercase is
    # invalid PETSCII source and ASCII uppercase would emit the wrong glyph
    # on the mixed-case charset. They go out as explicit bytes instead.
    for ch in text:
        if not (ch.isdigit() or ch == "."):
            raise SystemExit(f"gen_label_version: unexpected char {ch!r} in {text!r}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version-file", required=True, help="path to LABEL_VERSION")
    ap.add_argument("--build-file", required=True, help="path to BUILD_LABEL")
    ap.add_argument("--out", required=True, help="path to write labelver.s")
    args = ap.parse_args()

    ver = Path(args.version_file).read_text().strip()
    parts = ver.split(".")
    if len(parts) != 3 or not all(p.isdigit() for p in parts):
        raise SystemExit(f"gen_label_version: LABEL_VERSION must be MAJOR.MINOR.STAGE digits, got {ver!r}")

    build_line = Path(args.build_file).read_text().splitlines()[0].strip()
    if not build_line.isdigit():
        raise SystemExit(f"gen_label_version: BUILD_LABEL first line must be digits, got {build_line!r}")

    digits = f"{ver}.{build_line}"
    check_digits(digits)
    # $20 = space, $56 = unshifted PETSCII 'V' -> lowercase 'v' glyph on the
    # mixed-case charset (shifted $D6 would render uppercase 'V').
    name_hex = ", ".join(f"${b:02X}" for b in shifted_letter_bytes(APP_NAME)) + ", $20, $56"

    body = (
        "; SRC/EXTERNAL/LABEL/LABELVER.S -- GENERATED BY SCRIPTS/GEN_LABEL_VERSION.PY\n"
        "; DO NOT EDIT. DO NOT CHECK IN. REGENERATED AT BUILD TIME FROM\n"
        "; LABEL_VERSION + BUILD_LABEL (BOTH CHECKED IN, BOTH IN LABEL.REF.HEX'S\n"
        "; SOURCE-HASH GATE). SEE THE 2026-09-02 LABEL CASM-NATIVE MIGRATION PLAN.\n"
        ";\n"
        f"; RENDERS AS: {APP_NAME} V{digits}   (APP NAME UPPERCASE GLYPH,\n"
        "; LOWERCASE V, DIGITS -- MATCHING DEBUG'S BANNER FORMAT).\n"
        "\n"
        "LABELVERMSG:\n"
        f'    .BYTE {name_hex}    ; SHIFTED "{APP_NAME}" + SPACE + LOWERCASE V\n'
        f'    .BYTE "{digits}", ${PETSCII_CR:02X}, $00\n'
    )

    Path(args.out).write_text(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
