# cmake/KickAssembler.cmake
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Command64 project contributors
# Helper function to assemble 6502/6510 source files via KickAssembler

function(add_kickass_target TARGET_NAME)
    cmake_parse_arguments(KICKASS "" "ENTRY_FILE;OUTPUT_DIR" "SOURCES;DEPENDS;INCLUDE_DIRS" ${ARGN})
    
    if(NOT KICKASS_ENTRY_FILE)
        message(FATAL_ERROR "ENTRY_FILE is required for add_kickass_target")
    endif()
    
    if(NOT KICKASS_OUTPUT_DIR)
        set(KICKASS_OUTPUT_DIR "${CMAKE_BINARY_DIR}")
    endif()
    
    # Get absolute path for entry file
    get_filename_component(ENTRY_FILE_ABS "${KICKASS_ENTRY_FILE}" ABSOLUTE)
    get_filename_component(ENTRY_FILE_NAME "${ENTRY_FILE_ABS}" NAME_WE)
    
    set(OUTPUT_PRG "${KICKASS_OUTPUT_DIR}/${ENTRY_FILE_NAME}.prg")
    
    # Set search paths (-libdir)
    set(LIBDIR_ARGS "")
    foreach(INC_DIR ${KICKASS_INCLUDE_DIRS})
        get_filename_component(INC_DIR_ABS "${INC_DIR}" ABSOLUTE)
        list(APPEND LIBDIR_ARGS -libdir "${INC_DIR_ABS}")
    endforeach()
    
    # Get absolute path for output dir
    get_filename_component(OUTPUT_DIR_ABS "${KICKASS_OUTPUT_DIR}" ABSOLUTE)
    
    add_custom_command(
        OUTPUT "${OUTPUT_PRG}"
        COMMAND "${Java_JAVA_EXECUTABLE}" -jar "${KICKASS_JAR}" "${ENTRY_FILE_ABS}" ${LIBDIR_ARGS} -odir "${OUTPUT_DIR_ABS}"
        DEPENDS "${ENTRY_FILE_ABS}" ${KICKASS_SOURCES} ${KICKASS_DEPENDS}
        COMMENT "Assembling C64 binary: ${ENTRY_FILE_NAME}.prg"
        VERBATIM
    )
    
    # Create the custom target to be built by default
    add_custom_target(${TARGET_NAME} ALL DEPENDS "${OUTPUT_PRG}")
    
    # Expose the generated PRG file path as a property
    set_target_properties(${TARGET_NAME} PROPERTIES C64_PRG_PATH "${OUTPUT_PRG}")
endfunction()
 
# Helper function to define an external C64 application target with enforced versioning.
# It checks for a persistent build number file (BUILD_<NAME_UPPER>) in the source root
# and fails at configure time if it is missing, ensuring strict version enforcement.
#
# Phase 6B (Binary Relocator): the app is compiled twice, one page apart
# ($2600 and $2700), and tools/reloc.py diffs the two builds to produce a
# relocatable .prg carrying a high-byte relocation table + footer. This lets
# aptRelocate (loader.asm) patch the binary in place when it's loaded at a
# non-default page.
function(add_external_app TARGET_NAME ENTRY_FILE SOURCES_VAR DEFAULT_VERSION)
    string(TOUPPER "${TARGET_NAME}" TARGET_NAME_UPPER)
    set(BUILD_FILE "${CMAKE_SOURCE_DIR}/BUILD_${TARGET_NAME_UPPER}")
    set(INC_FILE "${CMAKE_BINARY_DIR}/build_${TARGET_NAME}.inc")

    # Enforce that the BUILD_<APP> file exists in the source directory
    if(NOT EXISTS "${BUILD_FILE}")
        message(FATAL_ERROR
            "\n"
            "========================================================================\n"
            " VERSIONING VIOLATION:\n"
            " External application target '${TARGET_NAME}' requires a persistent build\n"
            " counter file at: '${BUILD_FILE}'.\n"
            " Please create this file containing the starting build number (e.g. 1000)\n"
            " before configuring.\n"
            "========================================================================"
        )
    endif()

    # Dynamic build numbers custom command
    # Triggers the increment script only when dependency files change
    add_custom_command(
        OUTPUT "${INC_FILE}"
        COMMAND "${CMAKE_COMMAND}"
            -DBUILD_FILE="${BUILD_FILE}"
            -DINC_FILE="${INC_FILE}"
            -DDEFAULT_VERSION=${DEFAULT_VERSION}
            -DVAR_NAME="BUILD_NUMBER"
            -P "${CMAKE_SOURCE_DIR}/cmake/IncrementBuildNumber.cmake"
        DEPENDS ${${SOURCES_VAR}}
        COMMENT "Checking/Incrementing ${TARGET_NAME_UPPER} build counter"
    )

    get_filename_component(ENTRY_FILE_ABS "${ENTRY_FILE}" ABSOLUTE)
    get_filename_component(ENTRY_FILE_NAME "${ENTRY_FILE_ABS}" NAME_WE)

    # Per-config build directories, each carrying its own build_config.inc
    # that shadows the global one (verified: KickAssembler's -libdir is
    # first-match-wins, so listing the per-config dir before
    # CMAKE_BINARY_DIR overrides UserProgStart for this compile only).
    set(CONFIG_DIR_BASE "${CMAKE_BINARY_DIR}/build_${TARGET_NAME}_2600")
    set(CONFIG_DIR_NEXT "${CMAKE_BINARY_DIR}/build_${TARGET_NAME}_2700")
    file(WRITE "${CONFIG_DIR_BASE}/build_config.inc" "// Generated by CMake (Phase 6B relocation base build)\n.const UserProgStart = $2600\n")
    file(WRITE "${CONFIG_DIR_NEXT}/build_config.inc" "// Generated by CMake (Phase 6B relocation +1 page build)\n.const UserProgStart = $2700\n")

    # NOTE: -odir must NOT equal either -libdir entry. KickAssembler silently
    # falls through to the next -libdir for a bare #import when -odir collides
    # with a -libdir path (verified empirically) -- that would resolve
    # build_config.inc from CMAKE_BINARY_DIR (the global $2600 one) instead of
    # the per-config override, silently producing two identical $2600 builds.
    set(OUT_DIR_BASE "${CMAKE_BINARY_DIR}/out_${TARGET_NAME}_2600")
    set(OUT_DIR_NEXT "${CMAKE_BINARY_DIR}/out_${TARGET_NAME}_2700")
    set(PRG_BASE "${OUT_DIR_BASE}/${ENTRY_FILE_NAME}.prg")
    set(PRG_NEXT "${OUT_DIR_NEXT}/${ENTRY_FILE_NAME}.prg")
    set(OUTPUT_PRG "${CMAKE_BINARY_DIR}/${ENTRY_FILE_NAME}.prg")

    add_custom_command(
        OUTPUT "${PRG_BASE}"
        COMMAND "${Java_JAVA_EXECUTABLE}" -jar "${KICKASS_JAR}" "${ENTRY_FILE_ABS}"
            -libdir "${CONFIG_DIR_BASE}" -libdir "${CMAKE_BINARY_DIR}" -odir "${OUT_DIR_BASE}"
        DEPENDS "${ENTRY_FILE_ABS}" ${${SOURCES_VAR}} "${INC_FILE}" "${CONFIG_DIR_BASE}/build_config.inc"
        COMMENT "Assembling ${TARGET_NAME_UPPER} at $2600 (relocation base build)"
        VERBATIM
    )

    add_custom_command(
        OUTPUT "${PRG_NEXT}"
        COMMAND "${Java_JAVA_EXECUTABLE}" -jar "${KICKASS_JAR}" "${ENTRY_FILE_ABS}"
            -libdir "${CONFIG_DIR_NEXT}" -libdir "${CMAKE_BINARY_DIR}" -odir "${OUT_DIR_NEXT}"
        DEPENDS "${ENTRY_FILE_ABS}" ${${SOURCES_VAR}} "${INC_FILE}" "${CONFIG_DIR_NEXT}/build_config.inc"
        COMMENT "Assembling ${TARGET_NAME_UPPER} at $2700 (relocation +1 page build)"
        VERBATIM
    )

    add_custom_command(
        OUTPUT "${OUTPUT_PRG}"
        COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/tools/reloc.py" "${PRG_BASE}" "${PRG_NEXT}" "${OUTPUT_PRG}"
        DEPENDS "${PRG_BASE}" "${PRG_NEXT}" "${CMAKE_SOURCE_DIR}/tools/reloc.py"
        COMMENT "Building relocatable ${TARGET_NAME_UPPER}.prg"
        VERBATIM
    )

    add_custom_target(${TARGET_NAME} ALL DEPENDS "${OUTPUT_PRG}")
    set_target_properties(${TARGET_NAME} PROPERTIES C64_PRG_PATH "${OUTPUT_PRG}")
endfunction()
